export function getCountries() {
    return [
        { "id":"AF", "name":"Afghanistan"},
        { "id":"AL", "name":"Albania"},
        { "id":"DZ", "name":"Algeria"},
        { "id":"AO", "name":"Angola"},
        { "id":"AR", "name":"Argentina"},
        { "id":"AM", "name":"Armenia"},
        { "id":"AU", "name":"Australia"},
        { "id":"AT", "name":"Austria"},
        { "id":"AZ", "name":"Azerbaijan"},
        { "id":"BH", "name":"Bahrain"},
        { "id":"BD", "name":"Bangladesh"},
        { "id":"BY", "name":"Belarus"},
        { "id":"BE", "name":"Belgium"},
        { "id":"BJ", "name":"Benin"},
        { "id":"BT", "name":"Bhutan"},
        { "id":"BO", "name":"Bolivia"},
        { "id":"BA", "name":"Bosnia and Herzegovina"},
        { "id":"BW", "name":"Botswana"},
        { "id":"BR", "name":"Brazil"},
        { "id":"BN", "name":"Brunei"},
        { "id":"BG", "name":"Bulgaria"},
        { "id":"BF", "name":"Burkina Faso"},
        { "id":"BI", "name":"Burundi"},
        { "id":"KH", "name":"Cambodia"},
        { "id":"CM", "name":"Cameroon"},
        { "id":"CA", "name":"Canada"},
        { "id":"CV", "name":"Cape Verde"},
        { "id":"CF", "name":"Central African Republic"},
        { "id":"TD", "name":"Chad"},
        { "id":"CL", "name":"Chile"},
        { "id":"CN", "name":"China"},
        { "id":"CO", "name":"Colombia"},
        { "id":"KM", "name":"Comoros"},
        { "id":"CD", "name":"Democratic Republic of the Congo"},
        { "id":"CG", "name":"Republic of the Congo"},
        { "id":"CR", "name":"Costa Rica"},
        { "id":"CI", "name":"Cote d'Ivoire"},
        { "id":"HR", "name":"Croatia"},
        { "id":"CU", "name":"Cuba"},
        { "id":"CY", "name":"Cyprus"},
        { "id":"CZ", "name":"Czech Rep."},
        { "id":"DK", "name":"Denmark"},
        { "id":"DJ", "name":"Djibouti"},
        { "id":"DO", "name":"Dominican Republic"},
        { "id":"EC", "name":"Ecuador"},
        { "id":"EG", "name":"Egypt"},
        { "id":"SV", "name":"El Salvador"},
        { "id":"GQ", "name":"Equatorial Guinea"},
        { "id":"ER", "name":"Eritrea"},
        { "id":"EE", "name":"Estonia"},
        { "id":"ET", "name":"Ethiopia"},
        { "id":"FJ", "name":"Fiji"},
        { "id":"FI", "name":"Finland"},
        { "id":"FR", "name":"France"},
        { "id":"GA", "name":"Gabon"},
        { "id":"GM", "name":"Gambia"},
        { "id":"GE", "name":"Georgia"},
        { "id":"DE", "name":"Germany"},
        { "id":"GH", "name":"Ghana"},
        { "id":"GR", "name":"Greece"},
        { "id":"GT", "name":"Guatemala"},
        { "id":"GN", "name":"Guinea"},
        { "id":"GW", "name":"Guinea-Bissau"},
        { "id":"GY", "name":"Guyana"},
        { "id":"HT", "name":"Haiti"},
        { "id":"HN", "name":"Honduras"},
        { "id":"HK", "name":"Hong Kong"},
        { "id":"HU", "name":"Hungary"},
        { "id":"IS", "name":"Iceland"},
        { "id":"IN", "name":"India"},
        { "id":"ID", "name":"Indonesia"},
        { "id":"IR", "name":"Iran"},
        { "id":"IQ", "name":"Iraq"},
        { "id":"IE", "name":"Ireland"},
        { "id":"IL", "name":"Israel"},
        { "id":"IT", "name":"Italy"},
        { "id":"JM", "name":"Jamaica"},
        { "id":"JP", "name":"Japan"},
        { "id":"JO", "name":"Jordan"},
        { "id":"KZ", "name":"Kazakhstan"},
        { "id":"KE", "name":"Kenya"},
        { "id":"KP", "name":"North Korea"},
        { "id":"KR", "name":"South Korea"},
        { "id":"KW", "name":"Kuwait"},
        { "id":"KG", "name":"Kyrgyzstan"},
        { "id":"LA", "name":"Laos"},
        { "id":"LV", "name":"Latvia"},
        { "id":"LB", "name":"Lebanon"},
        { "id":"LS", "name":"Lesotho"},
        { "id":"LR", "name":"Liberia"},
        { "id":"LY", "name":"Libya"},
        { "id":"LT", "name":"Lithuania"},
        { "id":"LU", "name":"Luxembourg"},
        { "id":"MK", "name":"North Macedonia"},
        { "id":"MG", "name":"Madagascar"},
        { "id":"MW", "name":"Malawi"},
        { "id":"MY", "name":"Malaysia"},
        { "id":"ML", "name":"Mali"},
        { "id":"MR", "name":"Mauritania"},
        { "id":"MU", "name":"Mauritius"},
        { "id":"MX", "name":"Mexico"},
        { "id":"MD", "name":"Moldova"},
        { "id":"MN", "name":"Mongolia"},
        { "id":"ME", "name":"Montenegro"},
        { "id":"MA", "name":"Morocco"},
        { "id":"MZ", "name":"Mozambique"},
        { "id":"MM", "name":"Myanmar"},
        { "id":"NA", "name":"Namibia"},
        { "id":"NP", "name":"Nepal"},
        { "id":"NL", "name":"Netherlands"},
        { "id":"NZ", "name":"New Zealand"},
        { "id":"NI", "name":"Nicaragua"},
        { "id":"NE", "name":"Niger"},
        { "id":"NG", "name":"Nigeria"},
        { "id":"NO", "name":"Norway"},
        { "id":"OM", "name":"Oman"},
        { "id":"PK", "name":"Pakistan"},
        { "id":"PA", "name":"Panama"},
        { "id":"PG", "name":"Papua New Guinea"},
        { "id":"PY", "name":"Paraguay"},
        { "id":"PE", "name":"Peru"},
        { "id":"PH", "name":"Philippines"},
        { "id":"PL", "name":"Poland"},
        { "id":"PT", "name":"Portugal"},
        { "id":"PR", "name":"Puerto Rico"},
        { "id":"QA", "name":"Qatar"},
        { "id":"RO", "name":"Romania"},
        { "id":"RU", "name":"Russia"},
        { "id":"RW", "name":"Rwanda"},
        { "id":"SA", "name":"Saudi Arabia"},
        { "id":"SN", "name":"Senegal"},
        { "id":"RS", "name":"Serbia"},
        { "id":"SL", "name":"Sierra Leone"},
        { "id":"SG", "name":"Singapore"},
        { "id":"SK", "name":"Slovak Republic"},
        { "id":"SI", "name":"Slovenia"},
        { "id":"SB", "name":"Solomon Islands"},
        { "id":"SO", "name":"Somalia"},
        { "id":"ZA", "name":"South Africa"},
        { "id":"ES", "name":"Spain"},
        { "id":"LK", "name":"Sri Lanka"},
        { "id":"SD", "name":"Sudan"},
        { "id":"SR", "name":"Suriname"},
        { "id":"SZ", "name":"Swaziland"},
        { "id":"SE", "name":"Sweden"},
        { "id":"CH", "name":"Switzerland"},
        { "id":"SY", "name":"Syria"},
        { "id":"TW", "name":"Taiwan"},
        { "id":"TJ", "name":"Tajikistan"},
        { "id":"TZ", "name":"Tanzania"},
        { "id":"TH", "name":"Thailand"},
        { "id":"TG", "name":"Togo"},
        { "id":"TT", "name":"Trinidad and Tobago"},
        { "id":"TN", "name":"Tunisia"},
        { "id":"TR", "name":"Turkey"},
        { "id":"TM", "name":"Turkmenistan"},
        { "id":"UG", "name":"Uganda"},
        { "id":"UA", "name":"Ukraine"},
        { "id":"AE", "name":"United Arab Emirates"},
        { "id":"GB", "name":"United Kingdom"},
        { "id":"US", "name":"United States"},
        { "id":"UY", "name":"Uruguay"},
        { "id":"UZ", "name":"Uzbekistan"},
        { "id":"VE", "name":"Venezuela"},
        { "id":"PS", "name":"West Bank and Gaza"},
        { "id":"VN", "name":"Vietnam"},
        { "id":"YE", "name":"Yemen"},
        { "id":"ZM", "name":"Zambia"},
        { "id":"ZW", "name":"Zimbabwe"},
      ];
      
}

export default getCountries