export function getMapData(chart, colour) {
    let mapData = [
        { "id":"AF", "name":"Afghanistan", "value":0, "color": colour },
        { "id":"AL", "name":"Albania", "value":0, "color":colour },
        { "id":"DZ", "name":"Algeria", "value":0, "color":colour },
        { "id":"AO", "name":"Angola", "value":0, "color":colour },
        { "id":"AR", "name":"Argentina", "value":0, "color":colour },
        { "id":"AM", "name":"Armenia", "value":0, "color":colour },
        { "id":"AU", "name":"Australia", "value":0, "color":colour },
        { "id":"AT", "name":"Austria", "value":0, "color":colour },
        { "id":"AZ", "name":"Azerbaijan", "value":0, "color":colour },
        { "id":"BH", "name":"Bahrain", "value":0, "color": colour },
        { "id":"BD", "name":"Bangladesh", "value":0, "color": colour },
        { "id":"BY", "name":"Belarus", "value":0, "color":colour },
        { "id":"BE", "name":"Belgium", "value":0, "color":colour },
        { "id":"BJ", "name":"Benin", "value":0, "color":colour },
        { "id":"BT", "name":"Bhutan", "value":0, "color": colour },
        { "id":"BO", "name":"Bolivia", "value":0, "color":colour },
        { "id":"BA", "name":"Bosnia and Herzegovina", "value":0, "color":colour },
        { "id":"BW", "name":"Botswana", "value":0, "color":colour },
        { "id":"BR", "name":"Brazil", "value":0, "color":colour },
        { "id":"BN", "name":"Brunei", "value":0, "color": colour },
        { "id":"BG", "name":"Bulgaria", "value":0, "color":colour },
        { "id":"BF", "name":"Burkina Faso", "value":0, "color":colour },
        { "id":"BI", "name":"Burundi", "value":0, "color":colour },
        { "id":"KH", "name":"Cambodia", "value":0, "color": colour },
        { "id":"CM", "name":"Cameroon", "value":0, "color":colour },
        { "id":"CA", "name":"Canada", "value":0, "color":colour },
        { "id":"CV", "name":"Cape Verde", "value":0, "color":colour },
        { "id":"CF", "name":"Central African Rep.", "value":0, "color":colour },
        { "id":"TD", "name":"Chad", "value":0, "color":colour },
        { "id":"CL", "name":"Chile", "value":0, "color":colour },
        { "id":"CN", "name":"China", "value":0, "color": colour },
        { "id":"CO", "name":"Colombia", "value":0, "color":colour },
        { "id":"KM", "name":"Comoros", "value":0, "color":colour },
        { "id":"CD", "name":"Congo, Dem. Rep.", "value":0, "color":colour },
        { "id":"CG", "name":"Congo, Rep.", "value":0, "color":colour },
        { "id":"CR", "name":"Costa Rica", "value":0, "color":colour },
        { "id":"CI", "name":"Cote d'Ivoire", "value":0, "color":colour },
        { "id":"HR", "name":"Croatia", "value":0, "color":colour },
        { "id":"CU", "name":"Cuba", "value":0, "color":colour },
        { "id":"CY", "name":"Cyprus", "value":0, "color":colour },
        { "id":"CZ", "name":"Czech Rep.", "value":0, "color":colour },
        { "id":"DK", "name":"Denmark", "value":0, "color":colour },
        { "id":"DJ", "name":"Djibouti", "value":0, "color":colour },
        { "id":"DO", "name":"Dominican Rep.", "value":0, "color":colour },
        { "id":"EC", "name":"Ecuador", "value":0, "color":colour },
        { "id":"EG", "name":"Egypt", "value":0, "color":colour },
        { "id":"SV", "name":"El Salvador", "value":0, "color":colour },
        { "id":"GQ", "name":"Equatorial Guinea", "value":0, "color":colour },
        { "id":"ER", "name":"Eritrea", "value":0, "color":colour },
        { "id":"EE", "name":"Estonia", "value":0, "color":colour },
        { "id":"ET", "name":"Ethiopia", "value":0, "color":colour },
        { "id":"FJ", "name":"Fiji", "value":0, "color":colour },
        { "id":"FI", "name":"Finland", "value":0, "color":colour },
        { "id":"FR", "name":"France", "value":0, "color":colour },
        { "id":"GA", "name":"Gabon", "value":0, "color":colour },
        { "id":"GM", "name":"Gambia", "value":0, "color":colour },
        { "id":"GE", "name":"Georgia", "value":0, "color":colour },
        { "id":"DE", "name":"Germany", "value":0, "color":colour },
        { "id":"GH", "name":"Ghana", "value":0, "color":colour },
        { "id":"GR", "name":"Greece", "value":0, "color":colour },
        { "id":"GT", "name":"Guatemala", "value":0, "color":colour },
        { "id":"GN", "name":"Guinea", "value":0, "color":colour },
        { "id":"GW", "name":"Guinea-Bissau", "value":0, "color":colour },
        { "id":"GY", "name":"Guyana", "value":0, "color":colour },
        { "id":"HT", "name":"Haiti", "value":0, "color":colour },
        { "id":"HN", "name":"Honduras", "value":0, "color":colour },
        { "id":"HK", "name":"Hong Kong, China", "value":0, "color": colour },
        { "id":"HU", "name":"Hungary", "value":0, "color":colour },
        { "id":"IS", "name":"Iceland", "value":0, "color":colour },
        { "id":"IN", "name":"India", "value":0, "color": colour },
        { "id":"ID", "name":"Indonesia", "value":0, "color": colour },
        { "id":"IR", "name":"Iran", "value":0, "color": colour },
        { "id":"IQ", "name":"Iraq", "value":0, "color": colour },
        { "id":"IE", "name":"Ireland", "value":0, "color":colour },
        { "id":"IL", "name":"Israel", "value":0, "color": colour },
        { "id":"IT", "name":"Italy", "value":0, "color":colour },
        { "id":"JM", "name":"Jamaica", "value":0, "color":colour },
        { "id":"JP", "name":"Japan", "value":0, "color": colour },
        { "id":"JO", "name":"Jordan", "value":0, "color": colour },
        { "id":"KZ", "name":"Kazakhstan", "value":0, "color": colour },
        { "id":"KE", "name":"Kenya", "value":0, "color":colour },
        { "id":"KP", "name":"Korea, Dem. Rep.", "value":0, "color": colour },
        { "id":"KR", "name":"Korea, Rep.", "value":0, "color": colour },
        { "id":"KW", "name":"Kuwait", "value":0, "color": colour },
        { "id":"KG", "name":"Kyrgyzstan", "value":0, "color": colour },
        { "id":"LA", "name":"Laos", "value":0, "color": colour },
        { "id":"LV", "name":"Latvia", "value":0, "color":colour },
        { "id":"LB", "name":"Lebanon", "value":0, "color": colour },
        { "id":"LS", "name":"Lesotho", "value":0, "color":colour },
        { "id":"LR", "name":"Liberia", "value":0, "color":colour },
        { "id":"LY", "name":"Libya", "value":0, "color":colour },
        { "id":"LT", "name":"Lithuania", "value":0, "color":colour },
        { "id":"LU", "name":"Luxembourg", "value":0, "color":colour },
        { "id":"MK", "name":"Macedonia, FYR", "value":0, "color":colour },
        { "id":"MG", "name":"Madagascar", "value":0, "color":colour },
        { "id":"MW", "name":"Malawi", "value":0, "color":colour },
        { "id":"MY", "name":"Malaysia", "value":0, "color": colour },
        { "id":"ML", "name":"Mali", "value":0, "color":colour },
        { "id":"MR", "name":"Mauritania", "value":0, "color":colour },
        { "id":"MU", "name":"Mauritius", "value":0, "color":colour },
        { "id":"MX", "name":"Mexico", "value":0, "color":colour },
        { "id":"MD", "name":"Moldova", "value":0, "color":colour },
        { "id":"MN", "name":"Mongolia", "value":0, "color": colour },
        { "id":"ME", "name":"Montenegro", "value":0, "color":colour },
        { "id":"MA", "name":"Morocco", "value":0, "color":colour },
        { "id":"MZ", "name":"Mozambique", "value":0, "color":colour },
        { "id":"MM", "name":"Myanmar", "value":0, "color": colour },
        { "id":"NA", "name":"Namibia", "value":0, "color":colour },
        { "id":"NP", "name":"Nepal", "value":0, "color": colour },
        { "id":"NL", "name":"Netherlands", "value":0, "color":colour },
        { "id":"NZ", "name":"New Zealand", "value":0, "color":colour },
        { "id":"NI", "name":"Nicaragua", "value":0, "color":colour },
        { "id":"NE", "name":"Niger", "value":0, "color":colour },
        { "id":"NG", "name":"Nigeria", "value":0, "color":colour },
        { "id":"NO", "name":"Norway", "value":0, "color":colour },
        { "id":"OM", "name":"Oman", "value":0, "color": colour },
        { "id":"PK", "name":"Pakistan", "value":0, "color": colour },
        { "id":"PA", "name":"Panama", "value":0, "color":colour },
        { "id":"PG", "name":"Papua New Guinea", "value":0, "color":colour },
        { "id":"PY", "name":"Paraguay", "value":0, "color":colour },
        { "id":"PE", "name":"Peru", "value":0, "color":colour },
        { "id":"PH", "name":"Philippines", "value":0, "color": colour },
        { "id":"PL", "name":"Poland", "value":0, "color":colour },
        { "id":"PT", "name":"Portugal", "value":0, "color":colour },
        { "id":"PR", "name":"Puerto Rico", "value":0, "color":colour },
        { "id":"QA", "name":"Qatar", "value":0, "color": colour },
        { "id":"RO", "name":"Romania", "value":0, "color":colour },
        { "id":"RU", "name":"Russia", "value":0, "color":colour },
        { "id":"RW", "name":"Rwanda", "value":0, "color":colour },
        { "id":"SA", "name":"Saudi Arabia", "value":0, "color": colour },
        { "id":"SN", "name":"Senegal", "value":0, "color":colour },
        { "id":"RS", "name":"Serbia", "value":0, "color":colour },
        { "id":"SL", "name":"Sierra Leone", "value":0, "color":colour },
        { "id":"SG", "name":"Singapore", "value":0, "color": colour },
        { "id":"SK", "name":"Slovak Republic", "value":0, "color":colour },
        { "id":"SI", "name":"Slovenia", "value":0, "color":colour },
        { "id":"SB", "name":"Solomon Islands", "value":0, "color":colour },
        { "id":"SO", "name":"Somalia", "value":0, "color":colour },
        { "id":"ZA", "name":"South Africa", "value":0, "color":colour },
        { "id":"ES", "name":"Spain", "value":0, "color":colour },
        { "id":"LK", "name":"Sri Lanka", "value":0, "color": colour },
        { "id":"SD", "name":"Sudan", "value":0, "color":colour },
        { "id":"SR", "name":"Suriname", "value":0, "color":colour },
        { "id":"SZ", "name":"Swaziland", "value":0, "color":colour },
        { "id":"SE", "name":"Sweden", "value":0, "color":colour },
        { "id":"CH", "name":"Switzerland", "value":0, "color":colour },
        { "id":"SY", "name":"Syria", "value":0, "color": colour },
        { "id":"TW", "name":"Taiwan", "value":0, "color": colour },
        { "id":"TJ", "name":"Tajikistan", "value":0, "color": colour },
        { "id":"TZ", "name":"Tanzania", "value":0, "color":colour },
        { "id":"TH", "name":"Thailand", "value":0, "color": colour },
        { "id":"TG", "name":"Togo", "value":0, "color":colour },
        { "id":"TT", "name":"Trinidad and Tobago", "value":0, "color":colour },
        { "id":"TN", "name":"Tunisia", "value":0, "color":colour },
        { "id":"TR", "name":"Turkey", "value":0, "color":colour },
        { "id":"TM", "name":"Turkmenistan", "value":0, "color": colour },
        { "id":"UG", "name":"Uganda", "value":0, "color":colour },
        { "id":"UA", "name":"Ukraine", "value":0, "color":colour },
        { "id":"AE", "name":"United Arab Emirates", "value":0, "color": colour },
        { "id":"GB", "name":"United Kingdom", "value":0, "color":colour },
        { "id":"US", "name":"United States", "value":0, "color":colour },
        { "id":"UY", "name":"Uruguay", "value":0, "color":colour },
        { "id":"UZ", "name":"Uzbekistan", "value":0, "color": colour },
        { "id":"VE", "name":"Venezuela", "value":0, "color":colour },
        { "id":"PS", "name":"West Bank and Gaza", "value":0, "color": colour },
        { "id":"VN", "name":"Vietnam", "value":0, "color": colour },
        { "id":"YE", "name":"Yemen, Rep.", "value":0, "color": colour },
        { "id":"ZM", "name":"Zambia", "value":0, "color":colour },
        { "id":"ZW", "name":"Zimbabwe", "value":0, "color":colour }
      ];

       return mapData;

  }

export default getMapData